-- 1. Create Members/Profiles Table
CREATE TABLE IF NOT EXISTS public.members (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    its_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    full_name_ar TEXT,
    role TEXT NOT NULL DEFAULT 'photographer',
    mobile TEXT NOT NULL,
    email TEXT NOT NULL,
    city_raza TEXT,
    city_domicile TEXT,
    date_arrival DATE,
    mohalla TEXT,
    dp_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    sharaf_status TEXT NOT NULL DEFAULT 'none',
    sharaf_zone TEXT,
    sharaf_seat TEXT,
    cameras TEXT[],
    lenses TEXT[],
    other_equipment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Miqaats Table
CREATE TABLE IF NOT EXISTS public.miqaats (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL
);

-- 3. Create Sharaf Events Def Table
CREATE TABLE IF NOT EXISTS public.sharaf_events (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT false
);

-- 4. Create Zones Table
CREATE TABLE IF NOT EXISTS public.zones (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);

-- 5. Create Topics Table
CREATE TABLE IF NOT EXISTS public.topics (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL
);

-- 6. Create Sharaf Allocations Table
CREATE TABLE IF NOT EXISTS public.sharaf_allocations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    its_number TEXT NOT NULL REFERENCES public.members(its_id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    waaz_zone TEXT,
    mohalla TEXT,
    is_custom_zone BOOLEAN DEFAULT false,
    location TEXT,
    from_time TEXT,
    to_time TEXT
);

-- 7. Create Assignments Table
CREATE TABLE IF NOT EXISTS public.assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date DATE NOT NULL,
    miqaat_name TEXT,
    zone TEXT NOT NULL,
    topics JSONB, -- list of topics or touchpoints
    assigned_users TEXT[], -- Array of ITS numbers
    member_statuses JSONB DEFAULT '{}'::jsonb, -- map of ITS number -> status
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Assignment Notifications Table
CREATE TABLE IF NOT EXISTS public.assignment_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assignment_id UUID REFERENCES public.assignments(id) ON DELETE CASCADE,
    its_number TEXT NOT NULL,
    member_name TEXT NOT NULL,
    assignment_title TEXT NOT NULL,
    action TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    read BOOLEAN NOT NULL DEFAULT false
);

-- 9. Create Shot Reports Table
CREATE TABLE IF NOT EXISTS public.shot_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    its_number TEXT NOT NULL,
    user_name TEXT NOT NULL,
    assignment_id UUID REFERENCES public.assignments(id) ON DELETE SET NULL,
    assignment_title TEXT NOT NULL,
    drive_link TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT,
    grade TEXT NOT NULL DEFAULT 'Pending'
);

-- 10. Create Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.miqaats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sharaf_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sharaf_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignment_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shot_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 11. Create Security Policies

-- Members Policies
CREATE POLICY "Allow select for authenticated" ON public.members FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow individual insert" ON public.members FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow individual update" ON public.members FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Allow admin/coordinator updates" ON public.members FOR UPDATE TO authenticated 
    USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role IN ('admin', 'coordinator')));

-- Miqaats, Zones, Topics, Sharaf Events (Read all, write admin/coordinator)
CREATE POLICY "Allow read for authenticated" ON public.miqaats FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin write" ON public.miqaats FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Allow read for authenticated" ON public.zones FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin write" ON public.zones FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Allow read for authenticated" ON public.topics FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin write" ON public.topics FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Allow read for authenticated" ON public.sharaf_events FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin write" ON public.sharaf_events FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role = 'admin'));

-- Sharaf Allocations Policies
CREATE POLICY "Allow read for authenticated" ON public.sharaf_allocations FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow individual insert/update" ON public.sharaf_allocations FOR ALL TO authenticated 
    USING (its_number = (SELECT its_id FROM public.members WHERE id = auth.uid()))
    WITH CHECK (its_number = (SELECT its_id FROM public.members WHERE id = auth.uid()));
CREATE POLICY "Allow admin write allocations" ON public.sharaf_allocations FOR ALL TO authenticated
    USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role IN ('admin', 'coordinator')));

-- Assignments Policies
CREATE POLICY "Allow read assignments" ON public.assignments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow write assignments" ON public.assignments FOR ALL TO authenticated 
    USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role IN ('admin', 'coordinator')));

-- Assignment Notifications Policies
CREATE POLICY "Allow read notifications" ON public.assignment_notifications FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow write notifications" ON public.assignment_notifications FOR ALL TO authenticated USING (true);

-- Shot Reports Policies
CREATE POLICY "Allow read shot reports" ON public.shot_reports FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow user insert shot reports" ON public.shot_reports FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow user edit/delete own report" ON public.shot_reports FOR UPDATE TO authenticated 
    USING (its_number = (SELECT its_id FROM public.members WHERE id = auth.uid()));
CREATE POLICY "Allow admin manage shot reports" ON public.shot_reports FOR ALL TO authenticated 
    USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role IN ('admin', 'coordinator')));

-- Messages Policies
CREATE POLICY "Allow read messages" ON public.messages FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow individual insert messages" ON public.messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Allow individual edit messages" ON public.messages FOR UPDATE TO authenticated USING (auth.uid() = sender_id);
CREATE POLICY "Allow individual delete messages" ON public.messages FOR DELETE TO authenticated USING (auth.uid() = sender_id);

-- Storage Policies for 'dp-uploads' bucket
-- Note: Create the 'dp-uploads' bucket in Supabase UI first.
CREATE POLICY "Allow authenticated uploads" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'dp-uploads');
CREATE POLICY "Allow public read access to DPs" ON storage.objects FOR SELECT USING (bucket_id = 'dp-uploads');

-- 12. Create Public Function to resolve ITS ID to Email (for login)
CREATE OR REPLACE FUNCTION public.get_email_by_its_id(target_its_id TEXT)
RETURNS TABLE (email TEXT) SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY SELECT m.email FROM public.members m WHERE m.its_id = target_its_id;
END;
$$ LANGUAGE plpgsql;

-- 13. Create Trigger Function to automatically create profile in public.members upon auth signup
CREATE OR REPLACE FUNCTION public.handle_new_member()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.members (
    id,
    its_id,
    full_name,
    role,
    mobile,
    email,
    city_raza,
    mohalla,
    dp_url,
    cameras,
    lenses,
    other_equipment,
    status
  )
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'its_id', ''),
    COALESCE(new.raw_user_meta_data->>'full_name', ''),
    COALESCE(new.raw_user_meta_data->>'role', 'photographer'),
    COALESCE(new.raw_user_meta_data->>'mobile', ''),
    new.email,
    COALESCE(new.raw_user_meta_data->>'city_raza', 'Karachi'),
    COALESCE(new.raw_user_meta_data->>'mohalla', ''),
    new.raw_user_meta_data->>'dp_url',
    ARRAY(SELECT jsonb_array_elements_text(COALESCE(new.raw_user_meta_data->'cameras', '[]'::jsonb))),
    ARRAY(SELECT jsonb_array_elements_text(COALESCE(new.raw_user_meta_data->'lenses', '[]'::jsonb))),
    COALESCE(new.raw_user_meta_data->>'other_equipment', ''),
    'pending'
  )
  ON CONFLICT (id) DO UPDATE SET
    its_id = EXCLUDED.its_id,
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role,
    mobile = EXCLUDED.mobile,
    email = EXCLUDED.email,
    city_raza = EXCLUDED.city_raza,
    mohalla = EXCLUDED.mohalla,
    dp_url = EXCLUDED.dp_url,
    cameras = EXCLUDED.cameras,
    lenses = EXCLUDED.lenses,
    other_equipment = EXCLUDED.other_equipment;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution on auth.users insert
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_member();

