-- 1. Create Members/Profiles Table
CREATE TABLE IF NOT EXISTS public.members (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    its_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    full_name_ar TEXT,
    role TEXT NOT NULL DEFAULT 'photographer',
    mobile TEXT NOT NULL,
    email TEXT NOT NULL,
    city_raza TEXT,
    city_domicile TEXT,
    date_arrival DATE,
    mohalla TEXT,
    dp_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    sharaf_status TEXT NOT NULL DEFAULT 'none',
    sharaf_zone TEXT,
    sharaf_seat TEXT,
    cameras TEXT[],
    lenses TEXT[],
    other_equipment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Miqaats Table
CREATE TABLE IF NOT EXISTS public.miqaats (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL
);

-- 3. Create Sharaf Events Def Table
CREATE TABLE IF NOT EXISTS public.sharaf_events (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT false
);

-- 4. Create Zones Table
CREATE TABLE IF NOT EXISTS public.zones (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);

-- 5. Create Topics Table
CREATE TABLE IF NOT EXISTS public.topics (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL
);

-- 6. Create Sharaf Allocations Table
CREATE TABLE IF NOT EXISTS public.sharaf_allocations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    its_number TEXT NOT NULL REFERENCES public.members(its_id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    date DATE,
    location TEXT NOT NULL,
    zone TEXT,
    from_time TEXT,
    to_time TEXT,
    data_copying_deadline_date DATE,
    data_copying_deadline_time TEXT
);

-- 7. Create Assignments Table
CREATE TABLE IF NOT EXISTS public.assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date DATE NOT NULL,
    from_time TEXT,
    to_time TEXT,
    data_copying_deadline_date DATE,
    data_copying_deadline_time TEXT,
    miqaat_name TEXT,
    zone TEXT NOT NULL,
    topics JSONB, -- list of topics or touchpoints
    assigned_users TEXT[], -- Array of ITS numbers
    member_statuses JSONB DEFAULT '{}'::jsonb, -- map of ITS number -> status
    member_decline_reasons JSONB NOT NULL DEFAULT '{}'::jsonb, -- map of ITS number -> decline reason
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Assignment Notifications Table
CREATE TABLE IF NOT EXISTS public.assignment_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assignment_id UUID REFERENCES public.assignments(id) ON DELETE CASCADE,
    its_number TEXT NOT NULL,
    member_name TEXT NOT NULL,
    assignment_title TEXT NOT NULL,
    action TEXT NOT NULL,
    decline_reason TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    read BOOLEAN NOT NULL DEFAULT false
);

-- 9. Create Shot Reports Table
CREATE TABLE IF NOT EXISTS public.shot_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    its_number TEXT NOT NULL,
    user_name TEXT NOT NULL,
    assignment_id UUID REFERENCES public.assignments(id) ON DELETE SET NULL,
    assignment_title TEXT NOT NULL,
    drive_link TEXT,
    submission_method TEXT DEFAULT 'drive',
    touch_point_completion_mode TEXT DEFAULT 'exact',
    completion_percent_override INTEGER,
    completed_touch_points JSONB,
    admin_override JSONB,
    red_star_flags JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT,
    grade TEXT NOT NULL DEFAULT 'Pending'
);

-- 10. Create Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.miqaats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sharaf_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sharaf_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignment_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shot_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 11. Create Security Policies

-- Members Policies
CREATE POLICY "Allow select for authenticated" ON public.members FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow individual insert" ON public.members FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow individual update" ON public.members FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Allow admin/coordinator updates" ON public.members FOR UPDATE TO authenticated 
    USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role IN ('admin', 'coordinator')));

-- Miqaats, Zones, Topics, Sharaf Events (Read all, write admin/coordinator)
CREATE POLICY "Allow read for authenticated" ON public.miqaats FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin write" ON public.miqaats FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Allow read for authenticated" ON public.zones FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin write" ON public.zones FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Allow read for authenticated" ON public.topics FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin write" ON public.topics FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Allow read for authenticated" ON public.sharaf_events FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow admin write" ON public.sharaf_events FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role = 'admin'));

-- Sharaf Allocations Policies
CREATE POLICY "Allow read for authenticated" ON public.sharaf_allocations FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow individual insert/update" ON public.sharaf_allocations FOR ALL TO authenticated 
    USING (its_number = (SELECT its_id FROM public.members WHERE id = auth.uid()))
    WITH CHECK (its_number = (SELECT its_id FROM public.members WHERE id = auth.uid()));
CREATE POLICY "Allow admin write allocations" ON public.sharaf_allocations FOR ALL TO authenticated
    USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role IN ('admin', 'coordinator')));

-- Assignments Policies
CREATE POLICY "Allow select assignments for authorized users"
ON public.assignments FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.members m
        WHERE m.id = auth.uid()
        AND (
            m.role IN ('admin', 'coordinator')
            OR (m.hr_permissions IS NOT NULL AND (
                (m.hr_permissions->>'assignCoverage')::boolean = true OR
                (m.hr_permissions->>'viewAssignments')::boolean = true
            ))
            OR (public.assignments.assigned_users IS NOT NULL AND m.its_id = ANY(public.assignments.assigned_users))
        )
    )
);

CREATE POLICY "Allow write assignments" ON public.assignments FOR ALL TO authenticated 
    USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role IN ('admin', 'coordinator')));

-- Assignment Notifications Policies
CREATE POLICY "Allow admin and authorized hr read notifications" 
ON public.assignment_notifications FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.members m
        WHERE m.id = auth.uid() 
        AND (
            m.role IN ('admin', 'coordinator')
            OR (m.hr_permissions IS NOT NULL AND (
                (m.hr_permissions->>'assignCoverage')::boolean = true OR
                (m.hr_permissions->>'viewAssignments')::boolean = true
            ))
        )
    )
);

CREATE POLICY "Allow admin and authorized hr manage notifications" 
ON public.assignment_notifications FOR ALL TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.members 
        WHERE id = auth.uid() 
        AND (
            role IN ('admin', 'coordinator')
            OR (hr_permissions IS NOT NULL AND (
                (hr_permissions->>'assignCoverage')::boolean = true OR
                (hr_permissions->>'viewAssignments')::boolean = true
            ))
        )
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.members 
        WHERE id = auth.uid() 
        AND (
            role IN ('admin', 'coordinator')
            OR (hr_permissions IS NOT NULL AND (
                (hr_permissions->>'assignCoverage')::boolean = true OR
                (hr_permissions->>'viewAssignments')::boolean = true
            ))
        )
    )
);

-- Shot Reports Policies
CREATE POLICY "Allow read shot reports" ON public.shot_reports FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow user insert shot reports" ON public.shot_reports FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow user edit/delete own report" ON public.shot_reports FOR UPDATE TO authenticated 
    USING (its_number = (SELECT its_id FROM public.members WHERE id = auth.uid()));
CREATE POLICY "Allow admin manage shot reports" ON public.shot_reports FOR ALL TO authenticated 
    USING (EXISTS (SELECT 1 FROM public.members WHERE id = auth.uid() AND role IN ('admin', 'coordinator')));

-- Messages Policies
CREATE POLICY "Allow read messages" ON public.messages FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow individual insert messages" ON public.messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Allow individual edit messages" ON public.messages FOR UPDATE TO authenticated USING (auth.uid() = sender_id);
CREATE POLICY "Allow individual delete messages" ON public.messages FOR DELETE TO authenticated USING (auth.uid() = sender_id);

-- Storage Policies for 'dp-uploads' bucket
-- Note: Create the 'dp-uploads' bucket in Supabase UI first.
CREATE POLICY "Allow authenticated uploads" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'dp-uploads');
CREATE POLICY "Allow public read access to DPs" ON storage.objects FOR SELECT USING (bucket_id = 'dp-uploads');

-- 12. Create Public Function to resolve ITS ID to Email (for login)
CREATE OR REPLACE FUNCTION public.get_email_by_its_id(target_its_id TEXT)
RETURNS TABLE (email TEXT) SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY SELECT m.email FROM public.members m WHERE m.its_id = target_its_id;
END;
$$ LANGUAGE plpgsql;

-- 13. Create Trigger Function to automatically create profile in public.members upon auth signup
CREATE OR REPLACE FUNCTION public.handle_new_member()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.members (
    id,
    its_id,
    full_name,
    role,
    mobile,
    email,
    city_raza,
    mohalla,
    dp_url,
    cameras,
    lenses,
    other_equipment,
    status
  )
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'its_id', ''),
    COALESCE(new.raw_user_meta_data->>'full_name', ''),
    COALESCE(new.raw_user_meta_data->>'role', 'photographer'),
    COALESCE(new.raw_user_meta_data->>'mobile', ''),
    new.email,
    COALESCE(new.raw_user_meta_data->>'city_raza', 'Karachi'),
    COALESCE(new.raw_user_meta_data->>'mohalla', ''),
    new.raw_user_meta_data->>'dp_url',
    ARRAY(SELECT jsonb_array_elements_text(COALESCE(new.raw_user_meta_data->'cameras', '[]'::jsonb))),
    ARRAY(SELECT jsonb_array_elements_text(COALESCE(new.raw_user_meta_data->'lenses', '[]'::jsonb))),
    COALESCE(new.raw_user_meta_data->>'other_equipment', ''),
    'pending'
  )
  ON CONFLICT (id) DO UPDATE SET
    its_id = EXCLUDED.its_id,
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role,
    mobile = EXCLUDED.mobile,
    email = EXCLUDED.email,
    city_raza = EXCLUDED.city_raza,
    mohalla = EXCLUDED.mohalla,
    dp_url = EXCLUDED.dp_url,
    cameras = EXCLUDED.cameras,
    lenses = EXCLUDED.lenses,
    other_equipment = EXCLUDED.other_equipment;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 11. Create Data Dump tracking table
CREATE TABLE IF NOT EXISTS public.data_dumps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assignment_id UUID REFERENCES public.assignments(id) ON DELETE SET NULL,
    sharaf_allocation_id UUID REFERENCES public.sharaf_allocations(id) ON DELETE CASCADE,
    its_number TEXT NOT NULL REFERENCES public.members(its_id) ON DELETE CASCADE,
    event_name TEXT,
    date DATE,
    zone TEXT,
    card_received BOOLEAN NOT NULL DEFAULT false,
    card_received_at TIMESTAMP WITH TIME ZONE,
    card_received_by TEXT,
    card_copied BOOLEAN NOT NULL DEFAULT false,
    card_copied_at TIMESTAMP WITH TIME ZONE,
    card_copied_by TEXT,
    notes TEXT,
    card_notes TEXT,
    touch_point_completion_mode TEXT DEFAULT 'exact',
    completion_percent_override INTEGER,
    completed_touch_points JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_assignment_its_number UNIQUE (assignment_id, its_number),
    CONSTRAINT check_card_copied_requires_received CHECK (card_copied = false OR card_received = true)
);

ALTER TABLE public.data_dumps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admin and authorized hr select data dumps" 
ON public.data_dumps FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.members 
        WHERE id = auth.uid() 
        AND (
            role = 'admin' 
            OR (hr_permissions IS NOT NULL AND (hr_permissions->>'manageDataDump')::boolean = true)
        )
    )
);

CREATE POLICY "Allow admin and authorized hr write data dumps" 
ON public.data_dumps FOR ALL TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.members 
        WHERE id = auth.uid() 
        AND (
            role = 'admin' 
            OR (hr_permissions IS NOT NULL AND (hr_permissions->>'manageDataDump')::boolean = true)
        )
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.members 
        WHERE id = auth.uid() 
        AND (
            role = 'admin' 
            OR (hr_permissions IS NOT NULL AND (hr_permissions->>'manageDataDump')::boolean = true)
        )
    )
);

-- Trigger execution on auth.users insert
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_member();

-- 14. Create Miqaat Requests Table
CREATE TABLE IF NOT EXISTS public.miqaat_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    miqaat_name TEXT NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    notes TEXT,
    created_by TEXT,
    member_responses JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.miqaat_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow select miqaat requests for authorized users"
ON public.miqaat_requests FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.members m
        WHERE m.id = auth.uid()
        AND (
            m.role IN ('admin', 'coordinator')
            OR (m.hr_permissions IS NOT NULL AND (m.hr_permissions->>'assignCoverage')::boolean = true)
            OR (public.miqaat_requests.member_responses IS NOT NULL AND public.miqaat_requests.member_responses ? m.its_id)
        )
    )
);

CREATE POLICY "Allow all for admin and authorized hr miqaat requests"
ON public.miqaat_requests FOR ALL TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.members 
        WHERE id = auth.uid() 
        AND (
            role = 'admin' 
            OR (hr_permissions IS NOT NULL AND (hr_permissions->>'assignCoverage')::boolean = true)
        )
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.members 
        WHERE id = auth.uid() 
        AND (
            role = 'admin' 
            OR (hr_permissions IS NOT NULL AND (hr_permissions->>'assignCoverage')::boolean = true)
        )
    )
);

-- 15. Secure RPC: respond_to_miqaat_request
CREATE OR REPLACE FUNCTION public.respond_to_miqaat_request(
    target_request_id UUID,
    response_status TEXT,
    decline_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    calling_user_id UUID;
    calling_its TEXT;
    target_req RECORD;
    new_resp JSONB;
    updated_responses JSONB;
    now_iso TEXT;
    return_data JSONB;
BEGIN
    -- 1. Require authenticated user
    calling_user_id := auth.uid();
    IF calling_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required.';
    END IF;

    -- 2. Validate response_status
    IF response_status NOT IN ('accepted', 'declined') THEN
        RAISE EXCEPTION 'Invalid response status. Must be accepted or declined.';
    END IF;

    -- 3. Resolve auth.uid() -> members.its_id
    SELECT its_id INTO calling_its
    FROM public.members
    WHERE id = calling_user_id;

    IF calling_its IS NULL OR calling_its = '' THEN
        RAISE EXCEPTION 'Member profile not found for current user.';
    END IF;

    -- 4. Load the target miqaat request
    SELECT * INTO target_req
    FROM public.miqaat_requests
    WHERE id = target_request_id;

    IF target_req IS NULL THEN
        RAISE EXCEPTION 'Miqaat request not found.';
    END IF;

    -- 5. Verify current ITS exists in member_responses
    IF target_req.member_responses IS NULL OR NOT (target_req.member_responses ? calling_its) THEN
        RAISE EXCEPTION 'User % is not requested for this Miqaat.', calling_its;
    END IF;

    -- 6. Construct updated response for this member
    now_iso := to_char(timezone('utc'::text, now()), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
    
    new_resp := jsonb_build_object(
        'itsNumber', calling_its,
        'status', response_status,
        'respondedAt', now_iso
    );

    IF response_status = 'declined' AND decline_reason IS NOT NULL AND trim(decline_reason) <> '' THEN
        new_resp := new_resp || jsonb_build_object('declineReason', trim(decline_reason));
    END IF;

    -- 7. Update member_responses JSONB object
    updated_responses := jsonb_set(
        COALESCE(target_req.member_responses, '{}'::jsonb),
        ARRAY[calling_its],
        new_resp,
        true
    );

    -- 8. Persist update to public.miqaat_requests
    UPDATE public.miqaat_requests
    SET member_responses = updated_responses,
        updated_at = timezone('utc'::text, now())
    WHERE id = target_request_id;

    -- 9. Return updated row as JSON
    SELECT to_jsonb(r) INTO return_data
    FROM public.miqaat_requests r
    WHERE r.id = target_request_id;

    RETURN return_data;
END;
$$;

-- 16. Secure RPC: respond_to_assignment
CREATE OR REPLACE FUNCTION public.respond_to_assignment(
    target_assignment_id UUID,
    response_status TEXT,
    decline_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    calling_user_id UUID;
    calling_its TEXT;
    calling_name TEXT;
    target_as RECORD;
    updated_statuses JSONB;
    updated_reasons JSONB;
    notif_title TEXT;
    notif_msg TEXT;
    now_iso TIMESTAMPTZ;
    return_data JSONB;
BEGIN
    -- 1. Require authenticated user
    calling_user_id := auth.uid();
    IF calling_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required.';
    END IF;

    -- 2. Validate response_status
    IF response_status NOT IN ('accepted', 'declined') THEN
        RAISE EXCEPTION 'Invalid response status. Must be accepted or declined.';
    END IF;

    -- 3. Resolve auth.uid() -> members.its_id and full_name
    SELECT its_id, full_name INTO calling_its, calling_name
    FROM public.members
    WHERE id = calling_user_id;

    IF calling_its IS NULL OR calling_its = '' THEN
        RAISE EXCEPTION 'Member profile not found for current user.';
    END IF;

    -- 4. Load the target assignment
    SELECT * INTO target_as
    FROM public.assignments
    WHERE id = target_assignment_id;

    IF target_as IS NULL THEN
        RAISE EXCEPTION 'Assignment not found.';
    END IF;

    -- 5. Verify current ITS is in assigned_users
    IF target_as.assigned_users IS NULL OR NOT (calling_its = ANY(target_as.assigned_users)) THEN
        RAISE EXCEPTION 'User % is not assigned to this coverage task.', calling_its;
    END IF;

    -- 6. Update member_statuses
    updated_statuses := jsonb_set(
        COALESCE(target_as.member_statuses, '{}'::jsonb),
        ARRAY[calling_its],
        to_jsonb(response_status),
        true
    );

    -- 7. Update member_decline_reasons
    updated_reasons := COALESCE(target_as.member_decline_reasons, '{}'::jsonb);
    IF response_status = 'declined' AND decline_reason IS NOT NULL AND trim(decline_reason) <> '' THEN
        updated_reasons := jsonb_set(
            updated_reasons,
            ARRAY[calling_its],
            to_jsonb(trim(decline_reason)),
            true
        );
    ELSE
        -- If accepted, remove prior decline reason if present
        updated_reasons := updated_reasons - calling_its;
    END IF;

    -- 8. Persist update to public.assignments
    UPDATE public.assignments
    SET member_statuses = updated_statuses,
        member_decline_reasons = updated_reasons
    WHERE id = target_assignment_id;

    -- 9. Create atomic notification in public.assignment_notifications
    IF target_as.topics IS NOT NULL AND jsonb_typeof(target_as.topics) = 'array' AND jsonb_array_length(target_as.topics) > 0 THEN
        SELECT string_agg(elem::text, ', ') INTO notif_title
        FROM jsonb_array_elements_text(target_as.topics) AS elem;
    ELSE
        notif_title := COALESCE(target_as.zone, 'Coverage Task');
    END IF;

    IF response_status = 'accepted' THEN
        notif_msg := COALESCE(calling_name, 'Member') || ' confirmed ' || notif_title || ' coverage.';
    ELSE
        notif_msg := COALESCE(calling_name, 'Member') || ' declined ' || notif_title || ' coverage' ||
            CASE WHEN decline_reason IS NOT NULL AND trim(decline_reason) <> '' THEN ' (' || trim(decline_reason) || ')' ELSE '' END ||
            ' — 1 slot needs reassignment.';
    END IF;

    now_iso := timezone('utc'::text, now());

    INSERT INTO public.assignment_notifications (
        assignment_id,
        its_number,
        member_name,
        assignment_title,
        action,
        decline_reason,
        timestamp,
        read
    ) VALUES (
        target_assignment_id,
        calling_its,
        COALESCE(calling_name, calling_its),
        notif_msg,
        response_status,
        CASE WHEN response_status = 'declined' THEN trim(decline_reason) ELSE NULL END,
        now_iso,
        false
    );

    -- 10. Return updated assignment row as JSON
    SELECT to_jsonb(a) INTO return_data
    FROM public.assignments a
    WHERE a.id = target_assignment_id;

    RETURN return_data;
END;
$$;

REVOKE ALL ON FUNCTION public.respond_to_miqaat_request(UUID, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.respond_to_miqaat_request(UUID, TEXT, TEXT) FROM anon;
GRANT EXECUTE ON FUNCTION public.respond_to_miqaat_request(UUID, TEXT, TEXT) TO authenticated;

REVOKE ALL ON FUNCTION public.respond_to_assignment(UUID, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.respond_to_assignment(UUID, TEXT, TEXT) FROM anon;
GRANT EXECUTE ON FUNCTION public.respond_to_assignment(UUID, TEXT, TEXT) TO authenticated;



